### ISSUE TITLE
cloudbuild 4.5.1-dev not working

### ISSUE THREAD

**Issue by TheIsotopes** [betaflight/cloudbuild#22]
what's wrong? -> [build.betaflight.com/api/builds/03589d777802e13eb161941d082dc06e/log](https://build.betaflight.com/api/builds/03589d777802e13eb161941d082dc06e/log)

@haslinghuis pls, can you help?

**Comment by haslinghuis** [comment]
Guess the tag is missing. Also wonder if the tag should be `4.5.1` or `4.5-maintenance`.

**Comment by nerdCopter** [comment]
interesting. `4.5-maintenance` is the correct branch. ~~seemingly it cannot be checked out. wonder if a forced `git fetch --all` is in order.~~ :man_shrugging: 
@blckmn? 
ref: https://github.com/betaflight/cloudbuild/pull/21

edit: oh, i'm wrong on the git stuff, it is that there is no docker image for 4.5-maintenance

**Comment by TheIsotopes** [comment]
It would be nice if one of you could fix that.

**Comment by TheIsotopes** [comment]
4.5.1-dev cloudbuild working now, thx 👍 

[build.betaflight.com/api/builds/0f591c04758cef4199cf19f04ed42ddf/log](https://build.betaflight.com/api/builds/0f591c04758cef4199cf19f04ed42ddf/log)
