### ISSUE TITLE
can't create a 4.5.2 dev build

### ISSUE THREAD

**Issue by TheIsotopes** [betaflight/cloudbuild#24]
### Describe the bug

latest master can`t create a 4.5.2 dev build

### To Reproduce

try to create a 4.5.2 build

### Expected behavior

a 4.5.2 dev build support

### Configurator version

latest PWA master snapshot

**Comment by TheIsotopes** [comment]
thanks for moving @haslinghuis

**Comment by haslinghuis** [comment]
![image](https://github.com/user-attachments/assets/a0224fb6-f2d5-4649-bcf8-335c4f5e3fa7)

**Comment by TheIsotopes** [comment]
Unfortunately it doesn't seem to be working yet.
https://build.betaflight.com/api/builds/f3fdcb5460f083e19d425ebcb275efce/log

`{"type":"https://tools.ietf.org/html/rfc9110#section-15.5.5","title":"Not Found","status":404,"traceId":"00-d6f5f3b81ed208fc3c817b2d95ef0dbf-aa4836d974b8d686-00"}`

@blckmn @haslinghuis something on the server need to be repaired?

**Comment by blckmn** [comment]
Nothing needs to be repaired I'll be adding it shortly. Just a small amount of manual intervention.

**Comment by nerdCopter** [comment]
still failing 2 days later.

**Comment by TheIsotopes** [comment]
>  ... I'll be adding it shortly. Just a small amount of manual intervention.

@blckmn Unfortunately it still doesn't work today.

**Comment by blckmn** [comment]
Hmmm are you sure? What's your specific board? It may not be active for your FC

**Comment by TheIsotopes** [comment]
@blckmn MatekH743 and MatekF405TE both failed.

**Comment by blckmn** [comment]
Did the build fail or were you unable to select it?

**Comment by TheIsotopes** [comment]
both can be selected but the build failed.

[build.betaflight.com/api/builds/ccae8a0f5acc214cd424176aa39b8fa6/log](https://build.betaflight.com/api/builds/ccae8a0f5acc214cd424176aa39b8fa6/log)

[build.betaflight.com/api/builds/13724b9fbb6230770a9d3eed3eabc5c1/log](https://build.betaflight.com/api/builds/13724b9fbb6230770a9d3eed3eabc5c1/log)

**Comment by blckmn** [comment]
Confirmed now working:

https://[build.betaflight.com/api/builds/34890e3da8471956be70ac8a7f029074/log](https://build.betaflight.com/api/builds/34890e3da8471956be70ac8a7f029074/log)
