### ISSUE TITLE
Doesn't work for BF 4.4

### ISSUE THREAD

**Issue by dukevah** [betaflight/cloudbuild#9]
I pulled the image from Dockerhub and I also built the image by myself (for version 4.4). In both cases, the container is not capable of building the hex.
It shows the following error after cloning the repository inside the container:
```
Commencing the build (make OMNIBUSF4FW):
make: *** No rule to make target 'OMNIBUSF4FW'.  Stop.
make failed with 2
```
It works without any issue for image 4.5 and BF 4.5

**Comment by nerdCopter** [comment]
unified-target exists. requesting @blckmn to check.

**Comment by blckmn** [comment]
For 4.4 you make the target eg STM32F7X2 not the unified config name.

**Comment by vahdat-ab** [comment]
@blckmn right. Thanks. It worked. I assume the BF configurator will take care of applying the config file? How!
Is that correct or do I need to follow specific steps to build a board-specific hex file?
